---
kind: pipeline
type: docker
name: build docker image 

steps:
- name: pull submodules
  image: alpine/git
  commands:
    - git submodule update --init --recursive
- name: build relying-party 
  image: docker.ogkw.de/master-thesis/relying-party:buildenv
  commands:
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build . --config Debug --target relying-party
- name: build docker image
  image: plugins/docker
  settings:
    repo: docker.ogkw.de/master-thesis/relying-party
    registry: docker.ogkw.de
    tags: latest
    dockerfile: .docker/Dockerfile
    purge: true
trigger:
 event:
  - push
 branch:
  - master

---
kind: pipeline
type: docker
name: build docker buildenv image

steps:
- name: build buildenv image
  image: plugins/docker
  settings:
    repo: docker.ogkw.de/master-thesis/relying-party
    registry: docker.ogkw.de
    tags: buildenv
    dockerfile: .docker/Dockerfile.buildenv
    purge: true
trigger:
 event:
  - custom
 branch:
  - master