kind: pipeline
type: docker
name: default 

steps:
- name: submodules
  image: alpine/git
  commands:
    - git submodule update --init --recursive
- name: build docker dev image
  image: plugins/docker
  environment:
    GIT_TOKEN:
      from_secret: GIT_TOKEN
  settings:
    repo: docker.ogkw.de/master-thesis/relying-party
    registry: docker.ogkw.de
    tags: latest
    dockerfile: .docker/Dockerfile.dev
    purge: true
    build_args_from_env:
      - GIT_TOKEN
- name: build docker test image
  image: plugins/docker
  environment:
    GIT_TOKEN:
      from_secret: GIT_TOKEN
  settings:
    repo: docker.ogkw.de/master-thesis/relying-party
    registry: docker.ogkw.de
    tags: test
    dockerfile: .docker/Dockerfile.build
    purge: true
    build_args_from_env:
      - GIT_TOKEN
trigger:
 event:
  - custom
 branch:
   - master