version: '3'
services:
  relying-party:
   image: docker.ogkw.de/master-thesis/relying-party
   container_name: 'relying-party'
   stdin_open: true
   tty: true
   ports:
     - 80:80
   command: zsh
   user: 'vscode:1000'
  db:
   image: mariadb
   container_name: db
   restart: always
   environment: 
    MARIADB_ROOT_PASSWORD: dev
