version: '3'
services:
  keycape:
   build:
      context: ./
      dockerfile: .docker/Dockerfile.dev
   stdin_open: true
   tty: true
   user: 'vscode:1000'
   ports:
     - 80:80
     - 8000:8000
   restart: always
   environment:
    WEBAUTHN_RP_ID: localhost
    WEBAUTHN_RP_NAME: localhost
   depends_on:
      - db
      - redis
   volumes:
     - ./:/server
  db:
   image: mariadb
   restart: always
   environment: 
    MARIADB_ROOT_PASSWORD: dev
   volumes:
    - .docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    restart: always
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
