version: '3'
services:
  relying-party:
   build:
     context: .docker
     dockerfile: Dockerfile.dev
   container_name: 'relying-party'
   stdin_open: true
   tty: true
   ports:
     - 80:80
   command: zsh
   user: 'vscode:1000'
   restart: always
  rp_db:
   image: mariadb
   container_name: 'rp_db'
   restart: always
   environment: 
    MARIADB_ROOT_PASSWORD: dev
   volumes:
    - ./docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  rp_redis:
    image: redis:latest
    container_name: 'rp_redis'
    restart: always
