version: '3'
services:
  relying-party:
   image: idp
   container_name: 'relying-party'
   stdin_open: true
   tty: true
   ports:
     - 80:80
   restart: always
   environment:
    WEBAUTHN_RP_ID: localhost
    WEBAUTHN_RP_NAME: localhost
  db:
   image: mariadb
   container_name: rp_db
   restart: always
   environment: 
    MARIADB_ROOT_PASSWORD: dev
   volumes:
    - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    container_name: rp_redis
    restart: always
