FROM docker.ogkw.de/master-thesis/relying-party
COPY . /server

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100

WORKDIR /server/lib/libwebauthn-cpp/lib/tinycbor
RUN make lib/libtinycbor.a
WORKDIR /server/build
RUN cmake ..
RUN cmake --build . --config Debug --target relying-party

FROM docker.ogkw.de/master-thesis/relying-party

WORKDIR /server
COPY --from=0 /server/build/ ./

ENTRYPOINT [ "/server/relying-party" ]